AssociationState Protos for Validation Service
xmtp/proto pull request #160
Opened 2024-04-10 20:32 UTC by insipx

2024-04-16 18:19 UTC, neekolas approved these changes

2024-04-16 18:24 UTC, richardhuaaa requested changes

2024-04-16 18:24 UTC, richardhuaaa commented on proto/mls_validation/v1/service.proto
> +message GetAssociationStateResponse {
The server will need to know which addresses were affected, and whether they were associations or revocations, for the last appended identity update. What would be the best way to expose this?

2024-04-16 18:24 UTC, richardhuaaa commented on proto/mls_validation/v1/service.proto
> +message GetAssociationStateResponse {
https://github.com/xmtp/xmtp-node-go/blob/main/pkg/identity/api/v1/service.go#L53-L56

2024-04-16 18:27 UTC, richardhuaaa commented on proto/mls_validation/v1/service.proto
> +message GetAssociationStateResponse {
Perhaps an optional repeated field in `GetAssociationStateRequest` for `new_updates` or similar? Open to feedback here

2024-04-16 18:30 UTC, richardhuaaa commented on proto/mls_validation/v1/service.proto
> +message GetAssociationStateResponse {
I think we would also need this on the client for commit construction and validation: https://community.xmtp.org/t/xip-46-multi-wallet-identity/639#validating-the-other-proposals-in-the-commit-31

Perhaps the `GetAssociationStateRequest` can just have an `old_sequence_id` field, with all changes after that being tracked?

2024-04-17 19:32 UTC, richardhuaaa commented
Also, if validation fails, it will fail on a specific sequence number, and I assume you'll abort the rest of the process. Could we get the sequence number that failed, and the state + changes up to that point? This will help with handling concurrency on the server

2024-04-18 17:49 UTC, neekolas approved these changes

2024-04-21 00:49 UTC, richardhuaaa approved these changes

2024-04-22 15:50 UTC, merged