build: cut precommit hook, introduce proto-change test
xmtp/proto pull request #22
Opened 2022-11-09 22:33 UTC by dmccartney

2022-11-09 23:20 UTC, neekolas requested changes
I'm good with removing the build hook, but we still need the commit message hook. Otherwise commits won't generate releases on NPM.

2022-11-09 23:20 UTC, neekolas commented on .husky/commit-msg
> -npx commitlint --edit
We still need this to enforce the commit message conventions, which are used by semantic-release.

2022-11-10 13:54 UTC, neekolas commented on .husky/commit-msg
> -npx commitlint --edit
Now that this is going to be generating code for more platforms, we are probably going to have to rethink our conventions for semantic-release (should a breaking change to the Dart build really trigger a new release on the JS package? Probably not). But I think that for the time-being we should leave things as-is and update when we have a reasonable alternative.

2022-11-10 19:30 UTC, neekolas approved these changes

2022-11-10 20:15 UTC, dmccartney commented
This isn't quite working: the `protoc` for `generate.go` inside the `proto-change-test` workflow is having versioning and path issues (so it's giving us false-negatives -- it's failing when a proto file changes but not because of an unexpected diff). 

Instead of fighting through the go env quirks of this, I'm inclined to close this and revisit when time permits us to refactor codegen more generally. (But if someone else is inspired, feel free to pick this up and run with it.)

2022-11-10 20:15 UTC, closed without merging